INSERT INTO projects (slug, title, subtitle, category, short_desc, hero, image, client, industry, platform, services, overview, challenges, tech_stack, results, revenue_before, revenue_after, impact, live_link) VALUES
(
  'print-it',
  'PRINT-IT',
  'Campus Printing Platform',
  'Web App',
  'Campus printing platform officially adopted by Universal College of Engineering.',
  'A full-stack campus printing platform that completely eliminated the chaos of physical print queues. Students upload PDFs, pay online, and collect their prints.',
  '/printit1.0.png',
  'Universal College of Engineering',
  'Edtech / Services',
  'Web App',
  'Full-Stack Development, AWS Hosting, Payment Integration',
  'Built an end-to-end campus printing platform officially adopted by Universal College of Engineering, Mumbai. Reduced student queue wait time by 50%+.',
  ARRAY['Students wasted significant time standing in physical print queues.', 'No digital printing solution existed on campus.', 'Cash handling at the counter caused friction.'],
  ARRAY['React.js', 'Node.js', 'MongoDB', 'AWS S3', 'AWS EC2', 'Razorpay'],
  ARRAY['Officially adopted by Universal College of Engineering.', 'Student queue waiting time reduced by 50%+.', 'Profitable, scalable business model with active users.'],
  'Manual cash operations',
  'Profitable self-sustaining model',
  'The standard printing solution for the campus, drastically reducing wait times.',
  NULL
),
(
  'navrang',
  'NAVRANG',
  'D2C E-Commerce Brand',
  'E-Commerce',
  'A direct-to-consumer brand for Navratri collections.',
  'A direct-to-consumer brand for Navratri collections. Built everything from product catalog to Razorpay payments.',
  '/navrang0.png',
  'NavRang',
  'E-Commerce',
  'Web Platform',
  'Product Design, Web Development, Razorpay Integration',
  'Built NavRang — a direct-to-consumer brand for Navratri. A full-stack D2C eCommerce brand with real sales and profitability.',
  ARRAY['Offline Navratri sellers lack digital presence.', 'Complex checkout systems drop sales.'],
  ARRAY['Next.js', 'Tailwind CSS', 'Supabase', 'Razorpay'],
  ARRAY['Profitable venture with real sales.', 'Frictionless checkout experience.'],
  'No digital presence',
  'Real revenue generated during Navratri season.',
  'Enabled offline collections to reach a wider digital audience.',
  NULL
),
(
  'wheatflow',
  'WHEATFLOW',
  'B2B Dashboard for Grain Distribution',
  'Dashboard',
  'A production-grade B2B operations dashboard built for Anaj Sathi handling 2.4M+ records.',
  'A production-grade B2B operations dashboard built for Anaj Sathi handling 2.4M+ records with zero UI lag.',
  '/wheatflow1.png',
  'Anaj Sathi',
  'B2B Logistics',
  'Web Dashboard',
  'Full-Stack Dashboard, React Query, Supabase',
  'Built for Anaj Sathi — a grain distribution business. Handles massive data volumes, complex order grouping, driver logistics, automated financial tracking, and full fiscal-year management.',
  ARRAY['2.4 million+ records causing severe database bottlenecking.', 'Manual accounting lead to errors across multiple distributors.'],
  ARRAY['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'TanStack Query'],
  ARRAY['Optimized load times to under 200ms despite 2.4M rows.', 'Saved 15+ hours a week in manual entry.'],
  'Manual ledger & slow queries',
  'Fully automated, instant financial tracking',
  'Streamlined grain distribution tracking, resulting in zero calculation errors.',
  NULL
),
(
  'dr-doctor',
  'DR. DOCTOR',
  'SaaS for Healthcare Professionals',
  'SaaS App',
  'A patient management system for clinics across Mumbai.',
  'A patient queue management and electronic health records system currently adopted by clinics across Mumbai.',
  '/drdoctor1.png',
  'Multiple Clinics',
  'Healthcare SaaS',
  'Web App',
  'System Architecture, Product Development, Deployment',
  'Built a robust SaaS solution to manage clinic patients. Currently processing hundreds of patients daily.',
  ARRAY['Paper-based records get lost.', 'Patients face long wait times at clinics.'],
  ARRAY['React.js', 'Firebase', 'Tailwind CSS', 'Node.js'],
  ARRAY['Adopted by several prominent clinics.', 'Reduced wait times and lost records by 90%.'],
  'Manual tracking',
  'Digitized records and recurring SaaS revenue',
  'Modernized small clinics, making healthcare access smoother for patients.',
  NULL
);